title: Haroun Fujah # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>Hello there,<br>
  My name is Haroun Fujah, I am a private wealth relationship manager working in the investment banking/Finance sector of Lagos, Nigeria. 
  
   
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
